package pdf

import (
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu/model"
	"github.com/pdfcpu/pdfcpu/pkg/pdfcpu/types"
)

// Bounds on the name tree walk. A hostile file can nest or fan out without
// limit, and a cyclic /Kids would otherwise spin forever.
const (
	maxNameTreeDepth = 32
	maxNameTreeNodes = 4096
)

// namedDest resolves a named destination to its explicit destination array.
//
// pdfcpu's DereferenceDestArray reads XRefTable.Names, which only its
// validation pass populates; decant reads with ValidationRelaxed and never
// runs that pass, so the map is empty and every named destination fails. That
// is why this walks the tree directly. Doing so also fixes outline entries
// that use named destinations, which failed the same way.
//
// The catalog holds two forms. /Names /Dests is a name tree, which PDF 1.2
// onward and every TeX document uses. /Dests is the older flat dictionary.
// Both are checked, tree first.
func (d *Document) namedDest(name string) (types.Array, bool) {
	xref := d.ctx.XRefTable
	cat, err := xref.Catalog()
	if err != nil || cat == nil {
		return nil, false
	}

	if names, err := xref.DereferenceDict(cat["Names"]); err == nil && names != nil {
		if root, err := xref.DereferenceDict(names["Dests"]); err == nil && root != nil {
			budget := maxNameTreeNodes
			if arr, ok := d.searchNameTree(root, name, 0, &budget); ok {
				return arr, true
			}
		}
	}

	// The pre-1.2 flat form: /Dests maps names straight to destinations.
	if dests, err := xref.DereferenceDict(cat["Dests"]); err == nil && dests != nil {
		if v, found := dests.Find(name); found {
			return d.destValue(v)
		}
	}
	return nil, false
}

// searchNameTree looks name up in a name tree node.
//
// A node carries /Names (a leaf, holding key-value pairs sorted by key) or
// /Kids (intermediate nodes, each optionally bounded by /Limits). Limits are
// treated as a hint rather than a guarantee: a file whose limits are wrong or
// whose keys are misordered still resolves, just more slowly, which is the
// right trade for a format this often generated by hand.
func (d *Document) searchNameTree(node types.Dict, name string, depth int, budget *int) (types.Array, bool) {
	if depth >= maxNameTreeDepth || *budget <= 0 {
		return nil, false
	}
	*budget--
	xref := d.ctx.XRefTable

	if pairs, err := xref.DereferenceArray(node["Names"]); err == nil && pairs != nil {
		// Entries alternate key, value.
		for i := 0; i+1 < len(pairs); i += 2 {
			k, ok := stringValue(xref, pairs[i])
			if !ok || k != name {
				continue
			}
			return d.destValue(pairs[i+1])
		}
	}

	kids, err := xref.DereferenceArray(node["Kids"])
	if err != nil || kids == nil {
		return nil, false
	}
	for _, k := range kids {
		kid, err := xref.DereferenceDict(k)
		if err != nil || kid == nil {
			continue
		}
		if !withinLimits(xref, kid, name) {
			continue
		}
		if arr, ok := d.searchNameTree(kid, name, depth+1, budget); ok {
			return arr, true
		}
	}
	return nil, false
}

// withinLimits reports whether name can lie inside the node's /Limits range.
// A node with no or unreadable limits is always searched.
func withinLimits(xref *model.XRefTable, node types.Dict, name string) bool {
	lim, err := xref.DereferenceArray(node["Limits"])
	if err != nil || len(lim) < 2 {
		return true
	}
	lo, okLo := stringValue(xref, lim[0])
	hi, okHi := stringValue(xref, lim[1])
	if !okLo || !okHi {
		return true
	}
	return name >= lo && name <= hi
}

// destValue reads a name tree value, which is either the destination array
// itself or a dictionary carrying it under /D.
func (d *Document) destValue(v types.Object) (types.Array, bool) {
	xref := d.ctx.XRefTable
	resolved, err := xref.Dereference(v)
	if err != nil {
		return nil, false
	}
	switch t := resolved.(type) {
	case types.Array:
		return t, true
	case types.Dict:
		arr, err := xref.DereferenceArray(t["D"])
		if err != nil || arr == nil {
			return nil, false
		}
		return arr, true
	}
	return nil, false
}

// stringValue reads a name tree key, which the spec stores as a string but
// which some producers write as a name.
func stringValue(xref *model.XRefTable, o types.Object) (string, bool) {
	resolved, err := xref.Dereference(o)
	if err != nil {
		return "", false
	}
	switch t := resolved.(type) {
	case types.StringLiteral:
		return t.Value(), true
	case types.HexLiteral:
		return t.Value(), true
	case types.Name:
		return t.Value(), true
	}
	return "", false
}
